### ISSUE TITLE
Which license does this software has?

### ISSUE THREAD

**Issue by lquenti** [DaVikingCode/PDollar-Unity#4]
Under which conditions can I use it for non-commerical, open source software?
It would be lovely if you'd put it under a license like MIT

**Comment by alamboley** [comment]
The original source code is distributed through New BSD License http://depts.washington.edu/acelab/proj/dollar/pdollar.html

Not sure this repo can use MIT license!?

**Comment by lquenti** [comment]
BSD-3 is great! Would you mind adding the license to this repo as well?

I want to use it for my bachelors thesis, I will of course properly cite you and will open source the code once everything is done.

Let me create an PR now.

**Comment by alamboley** [comment]
Awesome, thank you! Good luck with your thesis!
